app:
  env: "dev"

paths:
  symmetric_key: "dev/symmetric_key.txt"
  public_key: "dev/public.pem"
  secret_key: "dev/private.pem"
  initial_file: "dev/text.txt"
  encrypted_file: "dev/encrypted_text.txt"
  decrypted_file: "dev/decrypted_text.txt"
